// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDbZgub8fcrUPgRPi41cB3YnV36AYOfq1Q',
    appId: '1:239227387324:web:de4a639a9f9cd43e2f7fb9',
    messagingSenderId: '239227387324',
    projectId: 'fixora-de5ce',
    authDomain: 'fixora-de5ce.firebaseapp.com',
    storageBucket: 'fixora-de5ce.firebasestorage.app',
    measurementId: 'G-SX5MR60B81',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC4rddylyUxeNVLTA8KLQobpLCpt5nhtFc',
    appId: '1:239227387324:android:10f3c014052234a32f7fb9',
    messagingSenderId: '239227387324',
    projectId: 'fixora-de5ce',
    storageBucket: 'fixora-de5ce.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCpbroCfxxrzRkYkwEJgmk6VJC6SWRXE6w',
    appId: '1:239227387324:ios:aba4dd43e4f63a6a2f7fb9',
    messagingSenderId: '239227387324',
    projectId: 'fixora-de5ce',
    storageBucket: 'fixora-de5ce.firebasestorage.app',
    iosBundleId: 'com.example.localfixers',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCpbroCfxxrzRkYkwEJgmk6VJC6SWRXE6w',
    appId: '1:239227387324:ios:aba4dd43e4f63a6a2f7fb9',
    messagingSenderId: '239227387324',
    projectId: 'fixora-de5ce',
    storageBucket: 'fixora-de5ce.firebasestorage.app',
    iosBundleId: 'com.example.localfixers',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDbZgub8fcrUPgRPi41cB3YnV36AYOfq1Q',
    appId: '1:239227387324:web:bcdfdae7040e54fd2f7fb9',
    messagingSenderId: '239227387324',
    projectId: 'fixora-de5ce',
    authDomain: 'fixora-de5ce.firebaseapp.com',
    storageBucket: 'fixora-de5ce.firebasestorage.app',
    measurementId: 'G-CFS63W38WN',
  );
}
